-- 1)
SELECT CEIL(ROW_NUMBER()OVER(ORDER BY EMPNO)/3.0) GRP,
EMPNO, EMPNAME
FROM EMP;

-- 2)
SELECT NTILE(4) OVER(ORDER BY EMPNO) GRP,
        EMPNO, EMPNAME 
FROM EMP;

-- 3)
SELECT JOBNO, LPAD('*', COUNT(*), '*') CNT
FROM CAREER
GROUP BY JOBNO
ORDER BY CNT;

-- 4)
SELECT 
MAX(DEPTNO_10) D10,
MAX(DEPTNO_20) D20,
MAX(DEPTNO_30) D30,
MAX(DEPTNO_40) D40
FROM (
 SELECT ROW_NUMBER()OVER(PARTITION BY DEPTNO ORDER BY EMPNO) RN,
CASE WHEN DEPTNO=10 THEN '*' ELSE NULL END DEPTNO_10,
CASE WHEN DEPTNO=20 THEN '*' ELSE NULL END DEPTNO_20,
CASE WHEN DEPTNO=30 THEN '*' ELSE NULL END DEPTNO_30,
CASE WHEN DEPTNO=40 THEN '*' ELSE NULL END DEPTNO_40
FROM CAREER
)
GROUP BY RN
ORDER BY 1 DESC, 2 DESC, 3 DESC, 4 DESC;