-- 1.
SELECT CASE GROUPING(DEPTNAME)
        WHEN 0 THEN DEPTNAME
        ELSE 'Total'
       END JOBNAME,
       COUNT(EMPNO) EMP_COUNT 
FROM CAREER JOIN DEPT USING(DEPTNO) JOIN EMP USING(EMPNO)
GROUP BY ROLLUP(DEPTNAME);

-- 2.
SELECT DEPTNAME, JOBNAME,
       CASE GROUPING(DEPTNAME) || GROUPING(JOBNAME)
        WHEN '00' THEN 'TOTAL BY DEPT AND JOB'
        WHEN '10' THEN 'TOTAL BY JOB'
        WHEN '01' THEN 'TOTAL BY DEPT'
        WHEN '11' THEN 'GRAND TOTAL for TABLE'
       END CATEGORY,
       COUNT(EMPNO) EMP_COUNT
FROM CAREER JOIN DEPT USING(DEPTNO) JOIN EMP USING(EMPNO) JOIN JOB USING(JOBNO)
GROUP BY CUBE(DEPTNAME, JOBNAME)
ORDER BY GROUPING(DEPTNAME), GROUPING(JOBNAME);

-- 3.
SELECT DEPTNAME, JOBNAME,
       CASE GROUPING(DEPTNAME) || GROUPING(JOBNAME)
        WHEN '00' THEN 'TOTAL BY DEPT AND JOB'
        WHEN '10' THEN 'TOTAL BY JOB'
        WHEN '01' THEN 'TOTAL BY DEPT'
        WHEN '11' THEN 'GRAND TOTAL for TABLE'
       END CATEGORY,
       SUM(SALVALUE) SALARY
FROM CAREER JOIN DEPT USING(DEPTNO) JOIN EMP USING(EMPNO) JOIN JOB USING(JOBNO) JOIN SALARY USING(EMPNO)
GROUP BY CUBE(DEPTNAME, JOBNAME)
ORDER BY GROUPING(DEPTNAME), GROUPING(JOBNAME);

-- 4.
SELECT DEPTNAME, JOBNAME, SUM(SALVALUE) SALARY,
       GROUPING(DEPTNAME) DEPT_SUBTOTAL,
       GROUPING(JOBNAME) JOB_SUBTOTAL
FROM CAREER JOIN DEPT USING(DEPTNO) JOIN EMP USING(EMPNO) JOIN JOB USING(JOBNO) JOIN SALARY USING(EMPNO)
GROUP BY CUBE(DEPTNAME, JOBNAME);

-- 5.
-- A)
SELECT EMPNAME, DEPTNAME, COUNT(EMPNO) OVER(PARTITION BY DEPTNAME) DEPTNAME_EMP_CNT,
JOBNAME, COUNT(JOBNAME) OVER(PARTITION BY JOBNAME) JOBNAME_EMP_CNT,
COUNT(*) OVER() AMOUNT
FROM CAREER JOIN DEPT USING(DEPTNO) JOIN EMP USING(EMPNO) JOIN JOB USING(JOBNO);

-- B)
SELECT STARTDATE, SALVALUE, 
SUM(SALVALUE) OVER (ORDER BY STARTDATE RANGE BETWEEN 90 PRECEDING AND CURRENT ROW) SPENDING_PATTERN
FROM CAREER JOIN EMP USING(EMPNO) JOIN SALARY USING(EMPNO);

-- C) 
SELECT JOBNAME, NUM_EMPS, SUM(ROUND(PCT)) PCT_OF_ALL_SALARIES
FROM (
 SELECT JOBNAME, COUNT(*)OVER(PARTITION BY JOBNAME) NUM_EMPS,
RATIO_TO_REPORT(SALVALUE)OVER()*100 PCT
FROM CAREER JOIN JOB USING(JOBNO) JOIN EMP USING(EMPNO) JOIN SALARY USING(EMPNO)
)
GROUP BY JOBNAME, NUM_EMPS;
